services:
  - type: web
    name: frontend
    env: static
    staticPublishPath: ./frontend/dist
    build:
      command: |
        cd frontend
        npm install
        npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html